### ISSUE TITLE
Issue with US vs DE Date

### ISSUE THREAD

**Issue by m4c3** [jiuka/checkmk_win_adsync#2]
Hi,
found an issue with the date parsing in https://github.com/jiuka/checkmk_win_adsync/blob/65bd8cac37a65040bc0acad8a1dfa4bd54244b15/checks/win_adsync_scheduler#L49

the agent returns the date in US notation:
`ValueError (time data u'6/4/2020 2:32:19 PM' does not match format '%d.%m.%Y %H:%M:%S')`

```
<<<win_adsync_scheduler:sep(0):encoding(cp437)>>>


AllowedSyncCycleInterval : 00:30:00
CurrentlyEffectiveSyncCycleInterval : 00:30:00
CustomizedSyncCycleInterval : 00:05:00
NextSyncCyclePolicyType : Delta
NextSyncCycleStartTimeInUTC : 6/4/2020 3:02:19 PM
PurgeRunHistoryInterval : 1.00:00:00
SyncCycleEnabled : True
MaintenanceEnabled : True
StagingModeEnabled : False
SchedulerSuspended : False
SyncCycleInProgress : False

<<<win_adsync_connector:sep(59):encoding(cp437)>>>
sx.onmicrosoft.com - AAD Delta Import;success;8.504;06/04/2020 14:32:43;
sx.onmicrosoft.com - AAD Delta Synchronization;success;1.297;06/04/2020 14:32:48;
sx.onmicrosoft.com - AAD Export;success;31.864;06/04/2020 14:33:20;
example.com Delta Import;success;13.296;06/04/2020 14:32:34;
example.com Delta Synchronization;success;3.406;06/04/2020 14:32:47;
example.com Export;completed-export-errors;0.11;06/04/2020 14:33:21;
```

any idea for a convinient way to catch this?
thanks Matthias

**Comment by jiuka** [comment]
Hi Matthias

I added a fix in [datetime_parse](/jiuka/checkmk_win_adsync/tree/datetime_parse). It fixes the date generated and converts it from UTC in the check. Both the agent plugin and the check needs to be updated.

A test build can be found in the GH Workflow from this branch. https://github.com/jiuka/checkmk_win_adsync/actions/runs/125633927

Regards Marius

**Comment by m4c3** [comment]
Good Morning, looks good - thank you!
